import os
OUT = r"e:\ARABIC TOOLS\arabic-tools\components\UaeCorporateTaxCalculator.jsx"
lines = []
def w(s=""): lines.append(s)
w("\"use client\";")
w()
w("import { useState, useMemo, useCallback } from \"react\";")
w("import Link from \"next/link\";")
w("import {")
w("  CT_ZERO_RATE_LIMIT, NATURAL_PERSON_TURNOVER_LIMIT, TAXPAYER_TYPE,")
w("  calcStandardCT, calcQfzpCT, checkSBREligibility,")
w("  formatAED, sanitizeNumber, FTA_CT_URL, FTA_SBR_URL, FTA_NATURAL_URL,")
w("} from \"@/lib/uaeCorporateTaxConfig\";")
w()
w("function AedInput({ id, label, hint, value, onChange, optional = false }) {")
w("  return (")
w("    <div>")
w("      <label htmlFor={id} className=\"block text-xs font-bold text-ink-secondary mb-1\">")
w("        {label}{optional && <span className=\"mr-1 text-ink-muted font-normal\">(اختياري)</span>}")
w("      </label>")
w("      <div className=\"relative\">")
w("        <input id={id} type=\"number\" inputMode=\"decimal\" min=\"0\" value={value}")
w("          onChange={(e) => onChange(e.target.value)} placeholder=\"0\"")
w("          className=\"w-full rounded-xl border border-brand-border bg-white px-3.5 py-2.5 text-sm font-bold text-ink focus:border-brand focus:outline-none\" />")
w("        <span className=\"pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-xs font-bold text-ink-muted\">\u062f.\u0625</span>")
w("      </div>")
w("      {hint && <p className=\"mt-1 text-[11px] text-ink-muted leading-relaxed\">{hint}</p>}")
w("    </div>")
w("  );")
w("}")
w()
w("function TriToggle({ label, value, onChange }) {")
w("  return (")
w("    <div>")
w("      <p className=\"text-xs font-bold text-ink-secondary mb-2\">{label}</p>")
w("      <div className=\"grid grid-cols-3 gap-2 max-w-sm\">")
w("        {[{l:\"نعم\",v:true},{l:\"لا\",v:false},{l:\"غير متأكد\",v:null}].map(({l,v}) => (")
w("          <button key={l} type=\"button\" onClick={() => onChange(v)}")
w("            className={`rounded-xl border p-2.5 text-center text-xs font-bold transition-all ${value === v ? \"border-brand bg-brand-light text-brand-dark shadow-sm\" : \"border-brand-border bg-white text-ink-secondary hover:border-brand\"}`}>")
w("            {l}")
w("          </button>")
w("        ))}")
w("      </div>")
w("    </div>")
w("  );")
w("}")
w()
w("const TAXPAYER_OPTIONS = [")
w("  { val: TAXPAYER_TYPE.STANDARD,       label: \"🏢 شركة / شخص اعتباري\",            desc: \"شركة ذات مسؤولية محدودة أو أي كيان قانوني مسجّل\" },")
w("  { val: TAXPAYER_TYPE.NATURAL_PERSON, label: \"👤 شخص طبيعي يمارس نشاطاً تجارياً\", desc: \"فرد يمارس أعمالاً تجارية مستقلة أو مهنية في الإمارات\" },")
w("  { val: TAXPAYER_TYPE.FREE_ZONE,      label: \"🏙️ منشأة في منطقة حرة\",             desc: \"شركة مسجّلة في منطقة حرة إماراتية معتمدة\" },")
w("  { val: TAXPAYER_TYPE.UNSURE,         label: \"❓ غير متأكد\",                       desc: \"أحتاج توجيهاً حول نوع الخاضع للضريبة\" },")
w("];")
w()
w("export default function UaeCorporateTaxCalculator() {")
w("  const [taxpayerType, setTaxpayerType] = useState(TAXPAYER_TYPE.STANDARD);")
w("  const [annualRevenue,  setAnnualRevenue]  = useState(\"0\");")
w("  const [taxableIncome,  setTaxableIncome]  = useState(\"0\");")
w("  const [estimateMode,   setEstimateMode]   = useState(false);")
w("  const [estRevenue,     setEstRevenue]     = useState(\"0\");")
w("  const [estExpenses,    setEstExpenses]    = useState(\"0\");")
w("  const [estAdjustments, setEstAdjustments] = useState(\"0\");")
w("  const [estTaxLosses,   setEstTaxLosses]   = useState(\"0\");")
w("  const [npTurnover,     setNpTurnover]     = useState(\"0\");")
w("  const [isQFZP,              setIsQFZP]              = useState(null);")
w("  const [qualifyingIncome,    setQualifyingIncome]    = useState(\"0\");")
w("  const [nonQualifyingIncome, setNonQualifyingIncome] = useState(\"0\");")
w("  const [showSBR,           setShowSBR]           = useState(false);")
w("  const [sbrIsResident,     setSbrIsResident]     = useState(null);")
w("  const [sbrCurrentRevenue, setSbrCurrentRevenue] = useState(\"0\");")
w("  const [sbrPriorRevenue,   setSbrPriorRevenue]   = useState(\"0\");")
w("  const [sbrIsQFZP,         setSbrIsQFZP]         = useState(null);")
w("  const [sbrIsMNE,          setSbrIsMNE]          = useState(null);")
w("  const [showCalcDetails, setShowCalcDetails] = useState(false);")
w("  const [showPrint,       setShowPrint]       = useState(false);")
w()
w("  const estimatedTI = useMemo(() => {")
w("    if (!estimateMode) return null;")
w("    return Math.max(0, sanitizeNumber(estRevenue) - sanitizeNumber(estExpenses) + sanitizeNumber(estAdjustments) - sanitizeNumber(estTaxLosses));")
w("  }, [estimateMode, estRevenue, estExpenses, estAdjustments, estTaxLosses]);")
w()
w("  const effectiveTI = useMemo(() => {")
w("    if (estimateMode && estimatedTI !== null) return estimatedTI;")
w("    return sanitizeNumber(taxableIncome);")
w("  }, [estimateMode, estimatedTI, taxableIncome]);")
w()
w("  const stdResult  = useMemo(() => calcStandardCT(effectiveTI), [effectiveTI]);")
w("  const qfzpResult = useMemo(() => calcQfzpCT(qualifyingIncome, nonQualifyingIncome), [qualifyingIncome, nonQualifyingIncome]);")
w("  const sbrResult  = useMemo(() => checkSBREligibility({ isResident: sbrIsResident, currentRevenue: sbrCurrentRevenue, priorMaxRevenue: sbrPriorRevenue, isQFZP: sbrIsQFZP, isMNEAboveThreshold: sbrIsMNE }), [sbrIsResident, sbrCurrentRevenue, sbrPriorRevenue, sbrIsQFZP, sbrIsMNE]);")
w()
w("  const npTurnoverNum  = sanitizeNumber(npTurnover);")
w("  const npInScope      = npTurnoverNum > NATURAL_PERSON_TURNOVER_LIMIT;")
w("  const isFZQFZP       = taxpayerType === TAXPAYER_TYPE.FREE_ZONE && isQFZP === true;")
w("  const today          = new Date().toLocaleDateString(\"ar-AE\", { year: \"numeric\", month: \"long\", day: \"numeric\" });")
w()
w("  const handleReset = useCallback(() => {")
w("    setTaxpayerType(TAXPAYER_TYPE.STANDARD);")
w("    setAnnualRevenue(\"0\"); setTaxableIncome(\"0\");")
w("    setEstimateMode(false); setEstRevenue(\"0\"); setEstExpenses(\"0\"); setEstAdjustments(\"0\"); setEstTaxLosses(\"0\");")
w("    setNpTurnover(\"0\"); setIsQFZP(null); setQualifyingIncome(\"0\"); setNonQualifyingIncome(\"0\");")
w("    setShowSBR(false); setSbrIsResident(null); setSbrCurrentRevenue(\"0\"); setSbrPriorRevenue(\"0\"); setSbrIsQFZP(null); setSbrIsMNE(null);")
w("    setShowCalcDetails(false); setShowPrint(false);")
w("  }, []);")
w()
w("  const loadPreset = (id) => {")
w("    handleReset();")
w("    if      (id === \"ex1\") { setTimeout(()=>{ setTaxableIncome(\"300000\"); },0); }")
w("    else if (id === \"ex2\") { setTimeout(()=>{ setTaxableIncome(\"1000000\"); setAnnualRevenue(\"1200000\"); },0); }")
w("    else if (id === \"ex3\") { setTimeout(()=>{ setAnnualRevenue(\"2400000\"); setTaxableIncome(\"500000\"); setShowSBR(true); setSbrIsResident(true); setSbrCurrentRevenue(\"2400000\"); setSbrPriorRevenue(\"0\"); setSbrIsQFZP(false); setSbrIsMNE(false); },0); }")
w("    else if (id === \"ex4\") { setTimeout(()=>{ setTaxpayerType(TAXPAYER_TYPE.NATURAL_PERSON); setNpTurnover(\"800000\"); },0); }")
w("    else if (id === \"ex5\") { setTimeout(()=>{ setTaxpayerType(TAXPAYER_TYPE.FREE_ZONE); setIsQFZP(true); setQualifyingIncome(\"2000000\"); setNonQualifyingIncome(\"200000\"); },0); }")
w("  };")
w()
w("  return (")
w("    <div className=\"space-y-6\">")
w()
w("      {/* Hero */}")
w("      <div className=\"rounded-2xl bg-hero-gradient p-6 text-white shadow-result\">")
w("        <div className=\"flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3\">")
w("          <div className=\"flex items-center gap-3\">")
w("            <span className=\"text-4xl\">🏛️</span>")
w("            <div>")
w("              <h1 className=\"text-xl sm:text-2xl font-black leading-tight\">حاسبة ضريبة الشركات في الإمارات</h1>")
w("              <p className=\"mt-1 text-sm text-white/85\">تقدير ضريبة الشركات وفق نسبتَي 0% و9% — المرسوم بقانون رقم 47 لسنة 2022</p>")
w("            </div>")
w("          </div>")
w("          <span className=\"shrink-0 rounded-full bg-white/20 border border-white/30 px-3 py-1 text-xs font-bold\">محدث 2026 — FTA</span>")
w("        </div>")
w("      </div>")
w()
w("      {/* Presets */}")
w("      <div className=\"rounded-2xl border border-brand-border bg-white p-4 shadow-card\">")
w("        <div className=\"flex items-center gap-2 mb-3\"><span>💡</span><span className=\"text-xs font-extrabold text-ink\">نماذج سريعة:</span></div>")
w("        <div className=\"flex flex-wrap gap-2\">")
w("          {[")
w("            { id:\"ex1\", label:\"دخل 300 ألف (0%)\",         cls:\"bg-emerald-50 border-emerald-200 text-emerald-800\" },")
w("            { id:\"ex2\", label:\"دخل مليون درهم (9%)\",       cls:\"bg-rose-50 border-rose-200 text-rose-800\"         },")
w("            { id:\"ex3\", label:\"2.4 مليون + فحص SBR\",       cls:\"bg-amber-50 border-amber-200 text-amber-800\"      },")
w("            { id:\"ex4\", label:\"شخص طبيعي 800 ألف\",          cls:\"bg-blue-50 border-blue-200 text-blue-800\"         },")
w("            { id:\"ex5\", label:\"QFZP — 2 مليون مؤهل\",        cls:\"bg-purple-50 border-purple-200 text-purple-800\"   },")
w("          ].map(p => (")
w("            <button key={p.id} type=\"button\" onClick={() => loadPreset(p.id)}")
w("              className={`rounded-lg border px-2.5 py-1 text-[11px] font-bold transition-all ${p.cls}`}>{p.label}</button>")
w("          ))}")
w("        </div>")
w("      </div>")
w()
w("      {/* Step 1 - taxpayer type */}")
w("      <div className=\"rounded-2xl border border-brand-border bg-white p-5 shadow-card space-y-4\">")
w("        <div className=\"flex items-center gap-2.5 border-b border-brand-border/60 pb-3\">")
w("          <span className=\"flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand text-xs font-black text-white\">١</span>")
w("          <h2 className=\"text-sm sm:text-base font-extrabold text-ink\">ما نوع الخاضع للضريبة؟</h2>")
w("        </div>")
w("        <div className=\"grid grid-cols-1 sm:grid-cols-2 gap-3\">")
w("          {TAXPAYER_OPTIONS.map(({ val, label, desc }) => (")
w("            <button key={val} type=\"button\" onClick={() => setTaxpayerType(val)}")
w("              className={`rounded-xl border p-3.5 text-right transition-all ${taxpayerType === val ? \"border-brand bg-brand-light shadow-sm\" : \"border-brand-border bg-white hover:border-brand\"}`}>")
w("              <p className={`text-sm font-extrabold ${taxpayerType === val ? \"text-brand-dark\" : \"text-ink\"}`}>{label}</p>")
w("              <p className=\"text-[11px] text-ink-muted mt-0.5 leading-relaxed\">{desc}</p>")
w("            </button>")
w("          ))}")
w("        </div>")
w("        {taxpayerType === TAXPAYER_TYPE.UNSURE && (")
w("          <div className=\"rounded-xl border border-amber-200 bg-amber-50/70 p-4 text-xs text-amber-900 leading-relaxed\">")
w("            <strong>توجيه عام:</strong> إذا كنت شركة مسجّلة قانونياً فاختر شركة. إذا كنت تعمل بصفتك الشخصية فاختر شخص طبيعي. يُنصح بمراجعة مستشار ضريبي مؤهل.")
w("          </div>")
w("        )}")
w("      </div>")
w()
w("      {/* Natural Person */}")
w("      {taxpayerType === TAXPAYER_TYPE.NATURAL_PERSON && (")
w("        <div className=\"rounded-2xl border border-brand-border bg-white p-5 shadow-card space-y-4\">")
w("          <div className=\"flex items-center gap-2.5 border-b border-brand-border/60 pb-3\">")
w("            <span className=\"flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand text-xs font-black text-white\">٢</span>")
w("            <span className=\"text-lg\">👤</span>")
w("            <h2 className=\"text-sm sm:text-base font-extrabold text-ink\">بيانات الشخص الطبيعي</h2>")
w("          </div>")
w("          <div className=\"rounded-xl border border-sky-100 bg-sky-50/60 p-3 text-xs text-sky-900 leading-relaxed\">")
w("            يدخل الشخص الطبيعي في نطاق ضريبة الشركات عندما يتجاوز <strong>دوران نشاطه التجاري الإماراتي 1,000,000 درهم</strong> خلال السنة الميلادية. لا يُحتسب: الرواتب، دخل الاستثمار الشخصي، أو دخل الاستثمار العقاري المؤهل.")
w("          </div>")
w("          <AedInput id=\"npTurnover\" label=\"إجمالي دوران النشاط التجاري خلال السنة الميلادية *\"")
w("            hint=\"مجموع إيرادات النشاط التجاري أو المهني فقط — لا تُدرج الراتب أو دخل الاستثمار.\"")
w("            value={npTurnover} onChange={setNpTurnover} />")
w("          {npTurnoverNum > 0 && (")
w("            <div className={`rounded-xl border p-4 space-y-2 ${npInScope ? \"border-rose-200 bg-rose-50/60\" : \"border-emerald-200 bg-emerald-50/60\"}`}>")
w("              <p className={`text-sm font-extrabold ${npInScope ? \"text-rose-800\" : \"text-emerald-800\"}`}>")
w("                {npInScope ? \"🔴 الدوران يتجاوز 1,000,000 درهم — قد تكون في نطاق ضريبة الشركات\" : \"🟢 الدوران دون حد 1,000,000 درهم — قد لا تكون مطالباً بالتسجيل\"}")
w("              </p>")
w("              <p className={`text-xs leading-relaxed ${npInScope ? \"text-rose-700\" : \"text-emerald-700\"}`}>")
w("                {npInScope ? \"يتجاوز الدوران حد التسجيل. ينبغي دراسة الالتزام بضريبة الشركات لدى FTA. يُنصح بمراجعة مستشار ضريبي.\" : \"قد لا تكون مطالباً بالتسجيل بناءً على هذا الشرط وحده. راجع دورياً عند نمو الأعمال.\"}")
w("              </p>")
w("            </div>")
w("          )}")
w("          {npInScope && (")
w("            <AedInput id=\"npTI\" label=\"الدخل الخاضع للضريبة التقديري *\"")
w("              hint=\"تنطبق نسبتا 0% (أول 375,000 د.إ) و9% (ما يزيد) كالشركات.\"")
w("              value={taxableIncome} onChange={setTaxableIncome} />")
w("          )}")
w("        </div>")
w("      )}")
w()
w("      {/* Free Zone */}")
w("      {taxpayerType === TAXPAYER_TYPE.FREE_ZONE && (")
w("        <div className=\"rounded-2xl border border-brand-border bg-white p-5 shadow-card space-y-4\">")
w("          <div className=\"flex items-center gap-2.5 border-b border-brand-border/60 pb-3\">")
w("            <span className=\"flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand text-xs font-black text-white\">٢</span>")
w("            <span className=\"text-lg\">🏙️</span>")
w("            <h2 className=\"text-sm sm:text-base font-extrabold text-ink\">بيانات منشأة المنطقة الحرة</h2>")
w("          </div>")
w("          <TriToggle label=\"هل أنت Qualifying Free Zone Person (QFZP) وفق الشروط الحالية؟\" value={isQFZP} onChange={setIsQFZP} />")
w("          {isQFZP === true && (")
w("            <div className=\"space-y-4\">")
w("              <div className=\"rounded-xl border border-purple-200 bg-purple-50/60 p-3 text-xs text-purple-900 leading-relaxed\">")
w("                <strong>نظام QFZP:</strong> الدخل المؤهل → 0% | الدخل غير المؤهل → 9% كاملة بدون نطاق إعفاء 375,000 درهم.")
w("              </div>")
w("              <div className=\"grid gap-4 sm:grid-cols-2\">")
w("                <AedInput id=\"qi\" label=\"الدخل المؤهل (Qualifying Income) *\"")
w("                  hint=\"دخل الأنشطة المؤهلة وفق لوائح FTA — يخضع لنسبة 0%.\"")
w("                  value={qualifyingIncome} onChange={setQualifyingIncome} />")
w("                <AedInput id=\"nqti\" label=\"الدخل غير المؤهل (Non-Qualifying Taxable Income) *\"")
w("                  hint=\"دخل الأنشطة المستبعدة أو غير المؤهلة — يخضع لنسبة 9% كاملة.\"")
w("                  value={nonQualifyingIncome} onChange={setNonQualifyingIncome} />")
w("              </div>")
w("              <div className=\"rounded-xl border border-amber-200 bg-amber-50/60 p-3 text-[11px] text-amber-900 leading-relaxed\">")
w("                ⚠️ وضع QFZP يستلزم استيفاء شروط متعددة: الأنشطة المؤهلة، الجوهر الاقتصادي، أسعار التحويل، ومتطلبات de minimis. هذه الحاسبة لا تُحقق من وضع QFZP.")
w("              </div>")
w("            </div>")
w("          )}")
w("          {isQFZP === false && (")
w("            <div className=\"space-y-4\">")
w("              <div className=\"rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs text-ink-secondary leading-relaxed\">")
w("                تنطبق القواعد المعيارية: 0% على أول 375,000 درهم، و9% على ما يتجاوزه.")
w("              </div>")
w("              <AedInput id=\"fzTI\" label=\"الدخل الخاضع للضريبة *\" hint=\"صافي الدخل الخاضع بعد التعديلات.\" value={taxableIncome} onChange={setTaxableIncome} />")
w("            </div>")
w("          )}")
w("          {isQFZP === null && (")
w("            <div className=\"rounded-xl border border-amber-200 bg-amber-50/60 p-3 text-xs text-amber-900 leading-relaxed\">")
w("              لتحديد وضع QFZP تحقق من: نوع المنطقة الحرة، طبيعة الأنشطة، الجوهر الاقتصادي. يُنصح بمراجعة مستشار ضريبي.")
w("            </div>")
w("          )}")
w("        </div>")
w("      )}")
w()
w("      {/* Standard inputs */}")
w("      {(taxpayerType === TAXPAYER_TYPE.STANDARD) && (")
w("        <div className=\"rounded-2xl border border-brand-border bg-white p-5 shadow-card space-y-4\">")
w("          <div className=\"flex items-center gap-2.5 border-b border-brand-border/60 pb-3\">")
w("            <span className=\"flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand text-xs font-black text-white\">٢</span>")
w("            <span className=\"text-lg\">📊</span>")
w("            <h2 className=\"text-sm sm:text-base font-extrabold text-ink\">البيانات المالية</h2>")
w("          </div>")
w("          <div className=\"rounded-xl border border-sky-100 bg-sky-50/60 p-3 text-xs text-sky-900 leading-relaxed\">")
w("            <strong>تنبيه:</strong> الإيرادات ≠ الدخل الخاضع للضريبة. الإيرادات لاختبارات الأهلية فقط. ضريبة الشركات تُحسب على <strong>الدخل الخاضع للضريبة</strong> بعد المصروفات والتعديلات المعتمدة.")
w("          </div>")
w("          <div className=\"grid gap-4 sm:grid-cols-2\">")
w("            <AedInput id=\"rev\" label=\"الإيرادات السنوية\" hint=\"إجمالي الإيرادات — يُستخدم لاختبارات الأهلية كتسهيلات الأعمال الصغيرة.\" value={annualRevenue} onChange={setAnnualRevenue} optional />")
w("            <AedInput id=\"ti\"  label=\"الدخل الخاضع للضريبة *\" hint=\"صافي الدخل الخاضع بعد كل المصروفات والتعديلات الضريبية.\" value={taxableIncome} onChange={setTaxableIncome} />")
w("          </div>")
w("          <div className=\"border-t border-brand-border/60 pt-3\">")
w("            <button type=\"button\" onClick={() => setEstimateMode(!estimateMode)} className=\"text-xs font-bold text-brand hover:underline\">")
w("              {estimateMode ? \"▲ إخفاء التقدير\" : \"▼ تقدير الدخل الخاضع من الإيرادات والمصروفات\"}")
w("            </button>")
w("            {estimateMode && (")
w("              <div className=\"mt-4 space-y-3\">")
w("                <div className=\"rounded-xl border border-amber-200 bg-amber-50/50 p-3 text-[11px] text-amber-900\">هذا تقدير أولي فقط — ليس إقراراً ضريبياً دقيقاً.</div>")
w("                <div className=\"grid gap-3 sm:grid-cols-2\">")
w("                  <AedInput id=\"eRev\"  label=\"الإيرادات\" value={estRevenue} onChange={setEstRevenue} />")
w("                  <AedInput id=\"eExp\"  label=\"المصروفات القابلة للخصم\" value={estExpenses} onChange={setEstExpenses} />")
w("                  <AedInput id=\"eAdj\"  label=\"تعديلات أخرى (إضافة)\" value={estAdjustments} onChange={setEstAdjustments} optional />")
w("                  <AedInput id=\"eLoss\" label=\"خسائر ضريبية مستخدمة\" value={estTaxLosses} onChange={setEstTaxLosses} optional />")
w("                </div>")
w("                {estimatedTI !== null && (")
w("                  <div className=\"rounded-xl border border-brand-border bg-brand-surface p-3\">")
w("                    <p className=\"text-[11px] font-bold text-brand-dark\">تقدير أولي للدخل الخاضع للضريبة:</p>")
w("                    <p className=\"text-lg font-black text-brand-dark mt-0.5\">{formatAED(estimatedTI)} د.إ</p>")
w("                    <p className=\"text-[10px] text-ink-muted\">تقدير استرشادي — ليس إقراراً ضريبياً.</p>")
w("                  </div>")
w("                )}")
w("              </div>")
w("            )}")
w("          </div>")
w("        </div>")
w("      )}")
w()
w("      {/* Visual Tax Breakdown Bar */}")
w("      {(taxpayerType !== TAXPAYER_TYPE.UNSURE) && (")
w("        <div className=\"rounded-2xl border border-brand-border bg-white p-5 shadow-card space-y-4\">")
w("          <div className=\"flex items-center justify-between\">")
w("            <h3 className=\"text-xs sm:text-sm font-extrabold text-ink flex items-center gap-1.5\"><span>📊</span><span>مؤشر الدخل الخاضع للضريبة:</span></h3>")
w("            {isFZQFZP ? (")
w("              <span className=\"text-[11px] font-bold text-purple-700\">دخل مؤهل: {formatAED(qfzpResult.qi)} | غير مؤهل: {formatAED(qfzpResult.nqti)}</span>")
w("            ) : (")
w("              <span className=\"text-[11px] font-bold text-brand-dark\">أعلى دخل محتسب: {formatAED(taxpayerType === TAXPAYER_TYPE.NATURAL_PERSON ? (npInScope ? sanitizeNumber(taxableIncome) : 0) : effectiveTI)} د.إ</span>")
w("            )}")
w("          </div>")
w("          {isFZQFZP ? (")
w("            <div className=\"space-y-2\">")
w("              <div className=\"relative h-8 w-full rounded-xl overflow-hidden border border-slate-200 flex\">")
w("                {qfzpResult.totalIncome > 0 && (")
w("                  <>")
w("                    <div className=\"bg-emerald-500 h-full flex items-center justify-center text-[10px] font-black text-white transition-all\"")
w("                      style={{ width: `${(qfzpResult.qi / qfzpResult.totalIncome * 100).toFixed(1)}%`, minWidth: qfzpResult.qi > 0 ? \"30px\" : \"0\" }}>")
w("                      {qfzpResult.qi > 0 && \"0%\"}")
w("                    </div>")
w("                    <div className=\"bg-rose-500 h-full flex items-center justify-center text-[10px] font-black text-white flex-1\">")
w("                      {qfzpResult.nqti > 0 && \"9%\"}")
w("                    </div>")
w("                  </>")
w("                )}")
w("              </div>")
w("              <div className=\"grid grid-cols-2 gap-2 text-[11px]\">")
w("                <div className=\"rounded-lg bg-emerald-50 border border-emerald-200 p-2.5 text-center\"><span className=\"font-extrabold text-emerald-800 block\">الدخل المؤهل → 0%</span><span className=\"text-emerald-700\">{formatAED(qfzpResult.qi)} د.إ</span></div>")
w("                <div className=\"rounded-lg bg-rose-50 border border-rose-200 p-2.5 text-center\"><span className=\"font-extrabold text-rose-800 block\">غير المؤهل → 9%</span><span className=\"text-rose-700\">{formatAED(qfzpResult.nqti)} د.إ</span></div>")
w("              </div>")
w("            </div>")
w("          ) : (")
w("            <div className=\"space-y-2\">")
w("              <div className=\"relative h-6 w-full rounded-xl bg-slate-100 overflow-hidden border border-slate-300\">")
w("                <div className=\"absolute left-0 top-0 bottom-0 bg-emerald-100 border-l border-emerald-300\" style={{ width: \"50%\" }} />")
w("                <div className=\"absolute left-[50%] top-0 bottom-0 bg-rose-100 border-l border-rose-300\" style={{ width: \"50%\" }} />")
w("                <div className=\"absolute top-0 bottom-0 bg-brand transition-all duration-500\"")
w("                  style={{ width: `${Math.min(100, Math.max(3, ((taxpayerType === TAXPAYER_TYPE.NATURAL_PERSON ? (npInScope ? sanitizeNumber(taxableIncome) : 0) : effectiveTI) / (CT_ZERO_RATE_LIMIT * 2)) * 100))}%` }} />")
w("              </div>")
w("              <div className=\"flex justify-between text-[10px] font-bold text-ink-muted px-1\">")
w("                <span>٠</span>")
w("                <span className=\"text-emerald-800\">375,000 د.إ<span className=\"block text-[9px] font-normal text-center\">حد 0%</span></span>")
w("                <span className=\"text-rose-800 text-left\">750,000+ د.إ<span className=\"block text-[9px] font-normal\">9%</span></span>")
w("              </div>")
w("              <div className=\"grid grid-cols-2 gap-2 text-[11px]\">")
w("                <div className=\"rounded-lg bg-emerald-50 border border-emerald-200 p-2.5 text-center\"><span className=\"font-extrabold text-emerald-800 block\">أول 375,000 درهم</span><span className=\"text-emerald-700 text-[10px]\">معفى — نسبة 0%</span></div>")
w("                <div className=\"rounded-lg bg-rose-50 border border-rose-200 p-2.5 text-center\"><span className=\"font-extrabold text-rose-800 block\">ما يتجاوز 375,000 درهم</span><span className=\"text-rose-700 text-[10px]\">يخضع لنسبة 9%</span></div>")
w("              </div>")
w("            </div>")
w("          )}")
w("        </div>")
w("      )}")
w()
